[DEFAULT]
TITLE = 'DEFAULT PARAMETERS'
SIZE = [297, 420]    # A3
LANDSCAPE = true
PPMM = 10
BLEED = [5,5]
OUTPUT_DIR = 'output/'
    [DEFAULT.LINE_STYLE]
    stroke = '#000'
    stroke-width = 10
    stroke-linecap = 'round'
