[DEFAULT]
TITLE = 'DEFAULT PARAMETERS'
BLEED = 20
RECURSION_DEPTH = 7
PPMM = 10
PAPER_SIZE = [297, 420]
MM_BLEED = 20
PRECISION = 0
OUTPUT_DIR = '../output/'
    [DEFAULT.LINE_STYLE]
    stroke = '#000'
    stroke-width = 10
    stroke-linecap = 'round'
